CREATE TABLE Patient(
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        full_name varchar(30) NOT NULL,
                        age int CHECK ( age > 0 ) NOT NULL ,
                        policy_number varchar(11) NOT NULL UNIQUE ,
                        phone_number varchar(11) NOT NULL
);

CREATE TABLE Doctor(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       full_name varchar(30) NOT NULL,
                       cabinet varchar(3) NOT NULL,
                       specialty_id int REFERENCES Specialty(id) ON DELETE SET NULL
);

CREATE TABLE Specialty(
                          id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(20) NOT NULL UNIQUE
);

CREATE TABLE Request(
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        patient_id int REFERENCES Patient(id) ON DELETE SET NULL,
                        doctor_id int REFERENCES Doctor(id) ON DELETE SET NULL,
                        desired_date DATE NOT NULL,
                        admission_date TIMESTAMP
);

CREATE TABLE Commentary(
                           id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           doctor_id int REFERENCES Doctor(id) ON DELETE SET NULL,
                           score int NOT NULL CHECK ( score > -1 ) CHECK ( score < 6 ),
                           description varchar(200)
);

INSERT INTO Patient(full_name, age, policy_number, phone_number) VALUES('Ivan Ivanov', 22, 11111111111, 89131111111);
INSERT INTO Specialty(name) VALUES('Dentist');
INSERT INTO Doctor(full_name, cabinet, specialty_id) VALUES('Petr Semenov', 302, 1);
INSERT INTO Commentary(doctor_id, score, description) VALUES(1, 4, 'Good doctor, xd.');
INSERT INTO Request(patient_id, doctor_id, desired_date) VALUES(1,1,'2024-10-25');